amahi/platform

plugins/040-apps/app/views/apps/_app_available.html.slim
plugins/040-apps/app/views/apps/_app_installed.html.slim
plugins/080-settings/app/views/settings/themes.html.slim

Resolved a few w3c validation errors (as mentioned in the bug tracker)

w3c validation

---

app/models/host.rb

Fixes: https://bugs.amahi.org/issues/1547

Accept only integer values in IP address

---

app/assets/themes/default/stylesheets/style.css.scss
config/locales/en.yml
plugins/050-network/app/assets/javascripts/network.js.coffee
plugins/050-network/app/controllers/network_controller.rb
plugins/050-network/app/views/network/settings.html.slim
plugins/050-network/config/routes.rb

implement this feature https://bugs.amahi.org/issues/1696

Customize DHCP Lease Range

---

plugins/020-shares/app/controllers/shares_controller.rb
plugins/020-shares/app/views/shares/_share.html.slim

continue of this #118 
Fixes: https://bugs.amahi.org/issues/1361

print error message at failure of getting share size

---

app/assets/stylesheets/login.css.scss
app/assets/themes/default/stylesheets/style.css.scss
app/controllers/application_controller.rb
app/views/shared/_flash_messages.html.slim
app/views/user_sessions/new.html.slim

Bug #1608 fix when accessed from ip it generates a flash message

the dashboard shows a warning when being accessed as an IP address

---

app/views/layouts/_footer.html.slim
public/404.html
public/422.html
public/500.html

add troubleshoot link to dashboard and error pages

Add troubleshoot link

---

README.md

Admin password created by rake db:seed is "secretpassword" but in README file its mentioned "admin".
I checked the db/seeds.rb file and the password is `secretpassword` in that.

Update admin password

---

plugins/020-shares/app/assets/javascripts/shares.js.coffee

fixes https://bugs.amahi.org/issues/2206

Cosmetic issue when changing samba workgroup name

---

plugins/040-apps/app/views/apps/_app_failed.html.slim

Fixed Bug #1918
Link added to Wiki page

App Install Failure

---

app/assets/themes/default/stylesheets/style.css.scss
plugins/010-users/app/views/users/_auth.html.slim
plugins/010-users/app/views/users/_form.html.slim
plugins/020-shares/app/views/shares/index.html.slim
plugins/040-apps/app/views/apps/_app_available.html.slim
plugins/040-apps/app/views/apps/_app_installed.html.slim
plugins/040-apps/app/views/apps/installed.html.slim
plugins/080-settings/app/views/settings/themes.html.slim

1. Apps Subtab content was previously not in BS.
2. Updated share subtab grid

Updated Bootstrap : Apps subtab

---

app/assets/javascripts/application.js
app/assets/javascripts/lib/application.js.coffee
app/assets/themes/default/stylesheets/style.css.scss
app/assets/themes/empty/init.rb
app/assets/themes/empty/stylesheets/rtl.css.scss
app/assets/themes/empty/stylesheets/style.css.scss
app/views/layouts/_footer.html.slim
app/views/layouts/_header.html.slim
app/views/shared/_tabs.html.slim
plugins/020-shares/app/views/shares/index.html.slim

Changes are made in order to make a plain Bootstrap theme
1. Tabs are converted using the dropdown method.
2. Navbar round at corners fixed
3. Footer for default theme fixed

changes for plain BS

---

lib/platform.rb

This fixes the "unknown-platform" and "unknown-hda-ctl" issues on CentOS

Fix unknown platform on CentOS

---

Gemfile
Gemfile.lock
lib/amahi_news.rb

Fixed issue #163 
Previously:-
Updated:-

Fix #163 Convert news feed time to more readable format 

---

app/views/aliases/_step1.html.erb
app/views/hosts/_step1.html.erb

I observed this while doing erb -> slim conversions task.   :smile:

small fix: added missing tags

---

plugins/010-users/app/views/users/_user.html.slim
plugins/020-shares/app/views/shares/_share.html.slim
plugins/040-apps/app/views/apps/_app_available.html.slim
plugins/040-apps/app/views/apps/_app_installed.html.slim
plugins/050-network/app/views/network/_dns_alias.html.slim
plugins/050-network/app/views/network/_host.html.slim
plugins/080-settings/app/views/settings/_server.html.slim
public/themes/default/stylesheets/style.css

now, used more standard colors for hover effect

Added hover effect on apps table items

---

plugins/020-shares/app/views/shares/create.json.jbuilder
plugins/020-shares/app/views/shares/index.html.slim
plugins/050-network/app/views/network/_dns_alias_form.html.slim

Fixed issue#190 : solved share tab duplicate items bug

---

app/models/share.rb
plugins/020-shares/app/controllers/shares_controller.rb
plugins/050-network/app/views/network/_dns_alias.html.slim
plugins/050-network/app/views/network/_dns_alias_form.html.slim

1. Share controller internal server error fixed by also allowing tags params
2. Dna Alias tab js file not working, which is now fixed

Fixed share tab and dns alias tab bugs

---

app/models/share.rb

here, guest_writeable_changed? always returning false in after_save method. After moving this in before_save, it works well.

fixed share.rb bug for after_save trigger

---

plugins/010-users/app/views/users/_password.html.slim
plugins/010-users/app/views/users/_pin.html.slim

this pull request solved issue #199

added id tag in users password and pin form

---

script/install-app

this prevents installation from install-app script if another app is getting installed.

Added check in install script for detecting any previous app installation running

---

script/install-app

Revert "Added check in install script for detecting any previous app installation running"

---

app/views/shared/_flash_messages.html.slim

Screenshot with html parsing problem:-
Screenshot after fixing this problem:-

html parsing in flash message fixed

---

Dockerfile

Following the [best practices for writing Dockerfiles](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) I've make some small improvements on amahi's Dockerfile.
I think more things could be improved, like these steps:
```dockerfile
RUN gem install bundler --no-ri --no-rdoc
RUN gem install rails -v 4.2.8 --no-ri --no-rdoc
```
I didn't understand why install these gems, since we're gonna run `docker-compose run amahi_web bundle install
` after.

Improves Dockerfile

---

Dockerfile

According to best practices specified at docker docs,
1. We should always tag the version of an image explicitly in Dockerfile
2. Use COPY instead of ADD for files and folders to the docker container.

Improved Dockerfile based on best practices
